# Site Metadata
title: Alex Figueroa
tagline: iOS Engineer
url: https://alexanderfigueroa.com
enforce_ssl: alexanderfigueroa.com
baseurl: /
site_home: Blog
paginate: 10
include: [_pages]
exclude: [Gemfile , Gemfile.lock, LICENSE, README.md, CNAME, vendor, package.json, node_modules, gulpfile.js, Rakefile]
plugins: [jekyll-paginate]
highlighter: rouge

# Author
author:
  name: Alex Figueroa
  profile_image_url: https://www.gravatar.com/avatar/ecbaec4f458de7172daff03e1f20e677
  twitter_username: externconst
  five_hundred_username: externvar

# Permalinks
permalink: pretty
